import requests, time, sys
from lxml import html
from twilio.rest import Client
#import login
course = ""

client = Client("", "")

cookies = {
    'JSESSIONID': '',
    'o365_token': '',
    'SESSION_TOKEN': ''
}

headers = {
    'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
    'Accept-Language': 'en-US,en;q=0.9',
    'Cache-Control': 'max-age=0',
    'Connection': 'keep-alive',
    'Origin': 'https://ss2.sfcollege.edu',
    'Referer': 'https://ss2.sfcollege.edu/eSantaFe?hptAppId=SR1010E&hptExec=Y&hptRecord=SR1008UI1&hptUIRecordPackage=sr1008e.pkg.',
    'Sec-Fetch-Dest': 'frame',
    'Sec-Fetch-Mode': 'navigate',
    'Sec-Fetch-Site': 'same-origin',
    'Sec-Fetch-User': '?1',
    'Upgrade-Insecure-Requests': '1',
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36',
    'sec-ch-ua': '" Not A;Brand";v="99", "Chromium";v="100", "Google Chrome";v="100"',
    'sec-ch-ua-mobile': '?0',
    'sec-ch-ua-platform': '"Windows"',
}

params = {
    'hptAppId': 'SR1010E',
    'hptExec': 'Y',
    'hptRecord': 'SR1008UI1',
    'hptUIRecordPackage': 'sr1008e.pkg.',
}

data = [
    ('SHOW_OPEN', 'Y'),
    ('TERM-VAL', '1'),
    ('CRS_NUM', course),
    ('ORG-VAL', '1'),
    ('ORG_CD', '3110'),
    ('ORG_CD', '8810'),
    ('ORG_CD', '4111'),
    ('ORG_CD', '3390'),
    ('ORG_CD', '1470'),
    ('ORG_CD', '1910'),
    ('ORG_CD', '1210'),
    ('ORG_CD', '1810'),
    ('ORG_CD', '3331'),
    ('ORG_CD', '3330'),
    ('ORG_CD', '3740'),
    ('ORG_CD', '1860'),
    ('ORG_CD', '3920'),
    ('ORG_CD', '3910'),
    ('ORG_CD', '3320'),
    ('ORG_CD', '3120'),
    ('ORG_CD', '3121'),
    ('ORG_CD', '3220'),
    ('ORG_CD', '1820'),
    ('ORG_CD', '3410'),
    ('ORG_CD', '1490'),
    ('ORG_CD', '8210'),
    ('ORG_CD', '3360'),
    ('ORG_CD', '3812'),
    ('ORG_CD', '3830'),
    ('ORG_CD', '3810'),
    ('ORG_CD', '7180'),
    ('ORG_CD', '7130'),
    ('ORG_CD', '7140'),
    ('ORG_CD', '2110'),
    ('ORG_CD', '2120'),
    ('ORG_CD', '3710'),
    ('ORG_CD', '1220'),
    ('ORG_CD', '3230'),
    ('ORG_CD', '3240'),
    ('ORG_CD', '1720'),
    ('ORG_CD', '8410'),
    ('ORG_CD', '7190'),
    ('ORG_CD', '1710'),
    ('ORG_CD', '8110'),
    ('ORG_CD', '3250'),
    ('ORG_CD', '3730'),
    ('ORG_CD', '1305'),
    ('ORG_CD', '1310'),
    ('ORG_CD', '3385'),
    ('ORG_CD', '1406'),
    ('ORG_CD', '1405'),
    ('ORG_CD', '1311'),
    ('ORG_CD', '3720'),
    ('ORG_CD', '3721'),
    ('ORG_CD', '1460'),
    ('ORG_CD', '7191'),
    ('ORG_CD', '1960'),
    ('ORG_CD', '1830'),
    ('ORG_CD', '3880'),
    ('ORG_CD', '3520'),
    ('ORG_CD', '1120'),
    ('ORG_CD', '3160'),
    ('ORG_CD', '8310'),
    ('ORG_CD', '5110'),
    ('ORG_CD', '1970'),
    ('ORG_CD', '1110'),
    ('ORG_CD', '1410'),
    ('ORG_CD', '8250'),
    ('ORG_CD', '3366'),
    ('ORG_CD', '3365'),
    ('ORG_CD', '8720'),
    ('ORG_CD', '3860'),
    ('ORG_CD', '1480'),
    ('ORG_CD', '1313'),
    ('ORG_CD', '3711'),
    ('ORG_CD', '1510'),
    ('ORG_CD', '3325'),
    ('ORG_CD', '1610'),
    ('ORG_CD', '1605'),
    ('ORG_CD', '6115'),
    ('ORG_CD', '6110'),
    ('ORG_CD', '8920'),
    ('ORG_CD', '1250'),
    ('ORG_CD', '1260'),
    ('ORG_CD', '3260'),
    ('ORG_CD', '8510'),
    ('ORG_CD', '3610'),
    ('ORG_CD', '3130'),
    ('ORG_CD', '8610'),
    ('ORG_CD', '3150'),
    ('ORG_CD', '3811'),
    ('ORG_CD', '1420'),
    ('ORG_CD', '3940'),
    ('ORG_CD', '1840'),
    ('ORG_CD', '3285'),
    ('ORG_CD', '1850'),
    ('ORG_CD', '3370'),
    ('ORG_CD', '1980'),
    ('ORG_CD', '1495'),
    ('ORG_CD', '4110'),
    ('ORG_CD', '1930'),
    ('ORG_CD', '3290'),
    ('ORG_CD', '4112'),
    ('ORG_CD', '1430'),
    ('ORG_CD', '3295'),
    ('ORG_CD', '3210'),
    ('ORG_CD', '1940'),
    ('ORG_CD', '1950'),
    ('ORG_CD', '3291'),
    ('ORG_CD', '1440'),
    ('ORG_CD', '1450'),
    ('ORG_CD', '3281'),
    ('ORG_CD', '2210'),
    ('ORG_CD', '9310'),
    ('ORG_CD', '3280'),
    ('ORG_CD', '1445'),
    ('ORG_CD', '1620'),
    ('ORG_CD', '1230'),
    ('ORG_CD', '3395'),
    ('ORG_CD', '1815'),
    ('ORG_CD', 'ALL'),
    ('ORG_CD', ''),
    ('ORG_CD', ''),
    ('ORG_CD', ''),
    ('ORG_CD', ''),
    ('ORG_CD', ''),
    ('ORG_CD', ''),
    ('ORG_CD', ''),
    ('ORG_CD', ''),
    ('ORG_CD', ''),
    ('ORG_CD', ''),
    ('ORG_CD', ''),
    ('ORG_CD', ''),
    ('ORG_CD', ''),
    ('ORG_CD', ''),
    ('ORG_CD', ''),
    ('ORG_CD', ''),
    ('ORG_CD', ''),
    ('ORG_CD', ''),
    ('ORG_CD', ''),
    ('ORG_CD', ''),
    ('ORG_CD', ''),
    ('ORG_CD', ''),
    ('ORG_CD', ''),
    ('ORG_CD', ''),
    ('ORG_CD', ''),
    ('ORG_CD', ''),
    ('ORG_CD', ''),
    ('ORG_CD', ''),
    ('ORG_CD', ''),
    ('ORG_CD', ''),
    ('ORG_CD', ''),
    ('ORG_CD', ''),
    ('ORG_CD', ''),
    ('ORG_CD', ''),
    ('ORG_CD', ''),
    ('ORG_CD', ''),
    ('ORG_CD', ''),
    ('ORG_CD', ''),
    ('ORG_CD', ''),
    ('ORG_CD', ''),
    ('ORG_CD', ''),
    ('ORG_CD', ''),
    ('ORG_CD', ''),
    ('ORG_CD', ''),
    ('ORG_CD', ''),
    ('ORG_CD', ''),
    ('ORG_CD', ''),
    ('ORG_CD', ''),
    ('ORG_CD', ''),
    ('ORG_CD', ''),
    ('ORG_CD', ''),
    ('ORG_CD', ''),
    ('ORG_CD', ''),
    ('ORG_CD', ''),
    ('ORG_CD', ''),
    ('ORG_CD', ''),
    ('ORG_CD', ''),
    ('ORG_CD', ''),
    ('ORG_CD', ''),
    ('ORG_CD', ''),
    ('ORG_CD', ''),
    ('ORG_CD', ''),
    ('ORG_CD', ''),
    ('ORG_CD', ''),
    ('ORG_CD', ''),
    ('ORG_CD', ''),
    ('ORG_CD', ''),
    ('ORG_CD', ''),
    ('ORG_CD', ''),
    ('ORG_CD', ''),
    ('ORG_CD', ''),
    ('ORG_CD', ''),
    ('ORG_CD', ''),
    ('ORG_CD', ''),
    ('ORG_CD', ''),
    ('ORG_CD', ''),
    ('ORG_CD', ''),
    ('ORG_CD', ''),
    ('ORG_CD', ''),
    ('ORG_CD', ''),
    ('ORG_CD', ''),
    ('ORG_CD', ''),
    ('ORG_CD', ''),
    ('SITE_NAM', 'ANY                           '),
    ('D_ANY_FL', 'Y'),
    ('TIME_ANY_FL', 'Y'),
    ('ENTER-VAL', ''),
    ('ORG-VAL', '1'),
    ('ORG-LIMIT-CNT', '117'),
    ('TERM-LIMIT-CNT', '10'),
    ('BOXES_PASS_DES', ''),
    ('SESSION_LIST', ''),
    ('HID_TERM_YR_NAM', '2022'),
    ('HID_TERM_YR_NAM', '2022'),
    ('HID_TERM_YR_NAM', '2022'),
    ('HID_TERM_YR_NAM', '2022'),
    ('HID_TERM_YR_NAM', '2022'),
    ('HID_TERM_YR_NAM', '2022'),
    ('HID_TERM_YR_NAM', '2022'),
    ('HID_TERM_YR_NAM', '2022'),
    ('HID_TERM_YR_NAM', '2022'),
    ('HID_TERM_YR_NAM', '2022'),
    ('HID_TERM_YR_NAM', ''),
    ('HID_TERM_YR_NAM', ''),
    ('HID_TERM_YR_NAM', ''),
    ('HID_TERM_YR_NAM', ''),
    ('HID_TERM_YR_NAM', ''),
    ('HID_TERM_YR_NAM', ''),
    ('HID_TERM_YR_NAM', ''),
    ('HID_TERM_YR_NAM', ''),
    ('HID_TERM_YR_NAM', ''),
    ('HID_TERM_YR_NAM', ''),
    ('HID_TERM_NUM_CD_NAM', '1'),
    ('HID_TERM_NUM_CD_NAM', '1'),
    ('HID_TERM_NUM_CD_NAM', '1'),
    ('HID_TERM_NUM_CD_NAM', '1'),
    ('HID_TERM_NUM_CD_NAM', '1'),
    ('HID_TERM_NUM_CD_NAM', '2'),
    ('HID_TERM_NUM_CD_NAM', '2'),
    ('HID_TERM_NUM_CD_NAM', '2'),
    ('HID_TERM_NUM_CD_NAM', '2'),
    ('HID_TERM_NUM_CD_NAM', '2'),
    ('HID_TERM_NUM_CD_NAM', ''),
    ('HID_TERM_NUM_CD_NAM', ''),
    ('HID_TERM_NUM_CD_NAM', ''),
    ('HID_TERM_NUM_CD_NAM', ''),
    ('HID_TERM_NUM_CD_NAM', ''),
    ('HID_TERM_NUM_CD_NAM', ''),
    ('HID_TERM_NUM_CD_NAM', ''),
    ('HID_TERM_NUM_CD_NAM', ''),
    ('HID_TERM_NUM_CD_NAM', ''),
    ('HID_TERM_NUM_CD_NAM', ''),
    ('HID_SESSION_CD', ''),
    ('HID_SESSION_CD', 'A'),
    ('HID_SESSION_CD', 'B'),
    ('HID_SESSION_CD', 'D'),
    ('HID_SESSION_CD', 'G'),
    ('HID_SESSION_CD', ''),
    ('HID_SESSION_CD', 'A'),
    ('HID_SESSION_CD', 'B'),
    ('HID_SESSION_CD', 'D'),
    ('HID_SESSION_CD', 'G'),
    ('HID_SESSION_CD', ''),
    ('HID_SESSION_CD', ''),
    ('HID_SESSION_CD', ''),
    ('HID_SESSION_CD', ''),
    ('HID_SESSION_CD', ''),
    ('HID_SESSION_CD', ''),
    ('HID_SESSION_CD', ''),
    ('HID_SESSION_CD', ''),
    ('HID_SESSION_CD', ''),
    ('HID_SESSION_CD', ''),
]

while True:
    try:
        response = requests.post('https://ss2.sfcollege.edu/eSantaFe', headers=headers, params=params, cookies=cookies, data=data)
        print(response.text)
        print(response)
        tree = html.fromstring(response.text)
        print(tree.xpath('//*[@id="MForm"]/div[2]/div/text()')[0])
        if tree.xpath('//*[@id="MForm"]/div[2]/div/text()')[0] != "\r\n\t\t\t\t\t\t\tNo courses meet your selection criteria\t\t\r\n\t\t\t\t\t\t":
            print("No courses meet your selection criteria1111")
            client.messages.create(to="", from_="", body=f"Seat open SANTA FE")
    except:
        client.messages.create(to="", from_="", body=f"SF Broken")
        sys.exit()
    finally:
        time.sleep(5 * 60)